packages:
  - docs
  - e2e/node
  - packages/agent
  - packages/assets
  - packages/auth-client
  - packages/candid
  - packages/core
  - packages/identity
  - packages/identity-secp256k1
  - packages/migrate
  - packages/principal
onlyBuiltDependencies:
  - esbuild
  - sharp
overrides:
  devalue@<5.3.2: '>=5.3.2'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
