packages:
  - docs
  - e2e/node
  - packages/agent
  - packages/candid
  - packages/core
  - packages/identity
  - packages/migrate
  - packages/principal
onlyBuiltDependencies:
  - esbuild
  - sharp
