name: E2E Node Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node:
          - 20
          - 22
          - 24

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version: ${{ matrix.node }}

      - run: pnpm build

      - uses: dfinity/setup-dfx@main

      - name: running dfx
        run: pnpm run -F @e2e/node setup

      - name: Node.js e2e tests
        run: pnpm run -F @e2e/node e2e
        env:
          REPLICA_PORT: 4943

  aggregate:
    name: e2e:required
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
