name: E2E Tests

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node:
          - 20
          - 22
          - 24

    steps:
      - uses: actions/checkout@v6

      - name: Setup PNPM
        uses: dfinity/ci-tools/actions/setup-pnpm@main
        with:
          node_version: ${{ matrix.node }}

      - run: pnpm build

      - name: Ensure PocketIC binary
        working-directory: e2e/node
        run: node node_modules/@dfinity/pic/postinstall.mjs

      - name: Node.js e2e tests
        run: pnpm run -F @e2e/node e2e

  aggregate:
    name: e2e:required
    if: ${{ always() }}
    needs: [e2e]
    runs-on: ubuntu-latest
    steps:
      - name: check e2e test result
        if: ${{ needs.e2e.result != 'success' }}
        run: exit 1
